flowchart TD
    Start-->A
    A["run[echo #quot;hello#quot;]"]-->B(Hooray the command succeeded)
    B-->C["run[echo #quot;world#quot;]"]
    C-->|foo|D(Fooby)
    C--bar-->E(Barry)
    D & E --> End
