flowchart TD
    Start-->A[High Five yourself]
    A-->B[["run[echo #quot;hello#quot;]"]]
    B-->C{Flip Coin}
    C--Heads-->D(You Win!)
    C--Tails-->E(You Lose)--->F
    F{Try Again?}--Yes-->C
    F & D--->|No|G(End)
    