flowchart TD
    Start-->A[High Five yourself]
    A-->B[["run[echo #quot;hello#quot;]"]]
    B-->C{Flip Coin}
    C--Heads-->D(You Win!)
    D-->G
    C--Tails-->E(You Lose)
    E--->F
    F{Try Again?}--Yes-->C
    F--->|No|G(End)

