node       =  { marker ~ content ~ NEWLINE? }
breaker    =  { NEWLINE }
marker     =  { unordered | one_of | and_then | clipbo }
unordered  =  { "&" }
one_of     =  { "|" }
and_then   =  { "~" }
clipbo     =  { "=" }
content    = @{ char+ }
char       = _{ !(NEWLINE) ~ ANY }
WHITESPACE = _{ " " }
COMMENT    = _{ "//" ~ (!NEWLINE ~ ANY)* }
oats       =  { (node | break)+ }
oats_file  = _{ SOI ~ oats ~ EOI }
