node       =  { marker ~ content ~ _COMMENT? ~ NEWLINE? }
breaker    =  { NEWLINE }
marker     =  { unordered | one_of | and_then | optional | clipbo }
unordered  =  { "&" }
one_of     =  { "|" }
and_then   =  { "~" }
optional   =  { "?" }
clipbo     =  { "=" }
content    = @{ char+ }
char       = _{ !(NEWLINE | "//") ~ ANY }
WHITESPACE = _{ " " }
_COMMENT   = _{ "//" ~ (!NEWLINE ~ ANY)* ~ NEWLINE }
oats       =  { (node | breaker | _COMMENT)+ }
oats_file  = _{ SOI ~ oats ~ EOI }
